# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${HMR_PORT:-8080}:8080'
            - '3000:3000'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_DATABASE: 'aj_at2_pt2'
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${FORWARD_MONGO_PORT:-27017}:27017'
        networks:
            - sail
        volumes:
            # service initialisation scripts
            # - ./docker/mongo-entrypoint:/docker-entrypoint-initdb.d
            # named volumes
            - sail-mongodb:/data/db
            - sail-mongoconfig:/data/configdb
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - '8082:8082'
        networks:
            - sail
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: '${DB_USERNAME}'
            ME_CONFIG_MONGODB_ADMINPASSWORD: '${DB_PASSWORD}'
            ME_CONFIG_MONGODB_SERVER: mongodb
        depends_on:
            - mongodb


networks:
    sail:
        driver: bridge

volumes:
    sail-mongodb:
        driver: local
    sail-mongoconfig:
        driver: local
